import {useEffect, useRef, useState} from 'react';
import './cloud-tasks.css';
export type CloudTask = {id?:string; name?:string; description?:string; state?:string; error_message?:string};
export type CloudTaskSnapshot = {project?:string; checkedAt?:string; tasks:CloudTask[]};
const labels:Record<string,string>={READY:'排队中',RUNNING:'运行中',COMPLETED:'已完成',FAILED:'失败',CANCEL_REQUESTED:'正在取消',CANCELLED:'已取消',UNSUBMITTED:'未提交'};
export function CloudTasksPanel({onRefresh,onCancel}:{onRefresh:()=>Promise<CloudTaskSnapshot>;onCancel:(id:string)=>Promise<unknown>}) {
 const [snapshot,setSnapshot]=useState<CloudTaskSnapshot>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[automatic,setAutomatic]=useState(true),[cancelId,setCancelId]=useState(''),[requested,setRequested]=useState<string[]>([]);
 const alive=useRef(true),loading=useRef(false);
 const refreshRef=useRef(onRefresh);refreshRef.current=onRefresh;
 async function refresh(){if(loading.current)return;loading.current=true;setBusy(true);try{const next=await refreshRef.current();if(alive.current){setSnapshot(next);setError('');}}catch(reason){if(alive.current)setError(reason instanceof Error?reason.message:String(reason));}finally{loading.current=false;if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;void refresh();return()=>{alive.current=false;};},[]);
 useEffect(()=>{if(!automatic)return;const timer=setInterval(()=>{if(!document.hidden)void refresh();},10000);return()=>clearInterval(timer);},[automatic]);
 async function cancel(id:string){setCancelId(id);setError('');try{await onCancel(id);if(alive.current){setRequested(items=>[...items,id]);await refresh();}}catch(reason){if(alive.current)setError(reason instanceof Error?reason.message:String(reason));}finally{if(alive.current)setCancelId('');}}
 return <section className="earth-cloud-tasks" aria-label="实时云端任务"><header><div><h2>Earth Engine 云端任务</h2><p>直接读取当前项目的 Google 任务状态。</p></div><button disabled={busy} onClick={()=>void refresh()}>{busy?'正在读取…':'刷新'}</button></header><label><input type="checkbox" checked={automatic} onChange={event=>setAutomatic(event.target.checked)}/>每 10 秒刷新</label>{snapshot?<p className="earth-cloud-tasks__stamp">{snapshot.project} · 更新于 {snapshot.checkedAt?new Date(snapshot.checkedAt).toLocaleTimeString():'未知'}</p>:null}{error?<p role="alert">{error}{snapshot?' 上次状态已保留，当前状态尚未确认。':''}</p>:null}{snapshot?.tasks.length===0?<p>当前没有云端批处理任务。地图预览和即时统计不会生成批处理任务。</p>:null}<ul>{snapshot?.tasks.map((task,index)=>{const id=task.id||task.name;return <li key={id||index}><div><strong>{task.description||id||'未命名任务'}</strong><span>{labels[task.state||'']||task.state||'状态未知'}</span></div>{task.error_message?<p role="alert">{task.error_message}</p>:null}{id?<details><summary>任务标识</summary><code>{id}</code></details>:null}{id&&['READY','RUNNING'].includes(task.state||'')?<button disabled={Boolean(cancelId)||requested.includes(id)} onClick={()=>void cancel(id)}>{requested.includes(id)?'已请求取消':cancelId===id?'正在请求…':'取消这个任务'}</button>:null}</li>;})}</ul><p>云端任务完成后，仍需确认成果已下载；“已完成”不表示本地文件已就绪。</p></section>;
}
