import {useState} from 'react';
import type {LocalGISRunSummary} from './EarthDataDock';
export type MapOptions={title?:string;paperSize?:'A4'|'A3'|'Letter';orientation?:'landscape'|'portrait';legend?:boolean;scaleBar?:boolean;northArrow?:boolean};
export type GISDeliveryReceipt={path:string;version:number;runId:string;verifiedFiles:number};
export function GISDeliveryPanel({runs,onGenerate,onOpenReport}:{runs:LocalGISRunSummary[];onGenerate:(runId:string,mapOptions?:MapOptions)=>Promise<GISDeliveryReceipt>;onOpenReport:(path:string)=>Promise<void>}) {
 const completed=runs.filter(run=>run.status==='completed');
 const [runId,setRunId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<GISDeliveryReceipt>();
 const [mapOptions,setMapOptions]=useState<MapOptions>({paperSize:'A4',orientation:'landscape',legend:true,scaleBar:true,northArrow:true});
 const selected=completed.find(run=>run.runId===runId);
 async function generate(){if(!selected||busy)return;setBusy(true);setError('');try{setReceipt(await onGenerate(selected.runId,mapOptions));}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setBusy(false);}}
 return <section className="earth-delivery-panel" aria-label="制图交付"><h2>把确认的结果交出去</h2><p>选择一次已完成的本地分析，生成地图、统计表和可重新打开的空间数据。每次交付保存为新版本。</p><label>使用哪次结果<select aria-label="交付分析结果" value={runId} disabled={busy} onChange={event=>{setRunId(event.target.value);setReceipt(undefined);setError('');}}><option value="">选择已完成的分析</option>{completed.map(run=><option key={run.runId} value={run.runId}>{run.op==='site-selection'?`地块避让 ${run.params?.distance ?? ''} 米`:run.op} · {new Date(run.updatedAt).toLocaleString()} · {run.runId.slice(0,8)}</option>)}</select></label>{!completed.length?<p>还没有可交付的本地结果。先完成一次分析，再回到这里。</p>:null}{selected?<details><summary>核对这次分析的参数</summary><pre>{JSON.stringify({runId:selected.runId,parameters:selected.params},null,2)}</pre></details>:null}<fieldset disabled={busy}><legend>地图版式</legend><label>地图标题<input aria-label="地图标题" maxLength={160} value={mapOptions.title||''} onChange={event=>setMapOptions({...mapOptions,title:event.target.value})}/></label><label>纸张<select aria-label="纸张" value={mapOptions.paperSize} onChange={event=>setMapOptions({...mapOptions,paperSize:event.target.value as MapOptions['paperSize']})}><option>A4</option><option>A3</option><option>Letter</option></select></label><label>方向<select aria-label="方向" value={mapOptions.orientation} onChange={event=>setMapOptions({...mapOptions,orientation:event.target.value as MapOptions['orientation']})}><option value="landscape">横向</option><option value="portrait">纵向</option></select></label>{([['legend','图例'],['scaleBar','比例尺'],['northArrow','指北针']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={mapOptions[key]} onChange={event=>setMapOptions({...mapOptions,[key]:event.target.checked})}/>{label}</label>)}</fieldset><p>成果包含 HTML 报告、地图 PDF/SVG/PNG、统计表、原始结果和文件清单；矢量结果另外生成 GPKG。布局编辑与图册排版暂未提供。</p><button type="button" disabled={!selected||busy} onClick={()=>void generate()}>{busy?'正在生成并读回检查…':'生成成果包'}</button>{error?<p role="alert">{error}</p>:null}{receipt?<div role="status"><strong>第 {receipt.version} 版已保存</strong><p>已检查 {receipt.verifiedFiles} 个文件，结果来自 {receipt.runId.slice(0,8)}。</p><button type="button" onClick={()=>void onOpenReport(`${receipt.path}/report.html`).catch(reason=>setError(String(reason)))}>打开报告</button><details><summary>成果位置</summary><code>{receipt.path}</code></details></div>:null}</section>;
}
