import {useEffect,useState} from 'react';
import type {ProjectLayer} from './layer-catalog';
export function GISOperationPanel({layers,onRun,onPlan}:{layers:ProjectLayer[];onPlan?:(question:string)=>Promise<void>;onRun:(plan:{parcels:string;avoidance:string;distance:number;commandId:string})=>Promise<void>}) {
 const [question,setQuestion]=useState('比较这些候选地块的接入路线，先列出需要补充的数据。');
 const polygons=layers.filter(layer=>layer.geometryTypes.some(type=>type==='Polygon'||type==='MultiPolygon'));
 const [parcels,setParcels]=useState(''),[avoidance,setAvoidance]=useState(''),[distance,setDistance]=useState(200),[busy,setBusy]=useState(false),[error,setError]=useState(''),[completed,setCompleted]=useState(false);
 useEffect(()=>{if(!parcels&&polygons.length===1)setParcels(polygons[0].path);},[parcels,polygons]);
 const parcel=polygons.find(layer=>layer.path===parcels),exclusion=layers.find(layer=>layer.path===avoidance);
 const valid=Boolean(parcel&&exclusion&&parcel.id!==exclusion.id&&Number.isFinite(distance)&&distance>0&&distance<=100000);
 return <section className="earth-sources earth-spatial-workflow" aria-label="选址方案参数"><h2>筛选可用地块</h2><p>选择候选地块和需要避开的河流或区域，得到实际剩余范围。调整距离后可保留并比较两版方案。</p><label>在哪些地块中寻找<select aria-label="分析地块" value={parcels} disabled={busy} onChange={event=>{setParcels(event.target.value);setCompleted(false);}}><option value="">选择面图层</option>{polygons.map(layer=><option key={layer.id} value={layer.path}>{layer.name} · v{layer.revision}</option>)}</select></label>{!polygons.length?<p>先从数据库加载地块，或在地图上画出区域并保存为项目图层。</p>:null}<label>需要避开什么<select aria-label="分析避让图层" value={avoidance} disabled={busy} onChange={event=>{setAvoidance(event.target.value);setCompleted(false);}}><option value="">选择河流、设施或限制区图层</option>{layers.filter(layer=>layer.path!==parcels).map(layer=><option key={layer.id} value={layer.path}>{layer.name} · v{layer.revision}</option>)}</select></label><label>至少保持多远（米）<input aria-label="避让距离" type="number" min={1} max={100000} value={distance} disabled={busy} onChange={event=>{setDistance(Number(event.target.value));setCompleted(false);}}/></label><button disabled={busy||!valid} onClick={()=>{setBusy(true);setError('');setCompleted(false);void onRun({parcels,avoidance,distance,commandId:crypto.randomUUID()}).then(()=>setCompleted(true)).catch(reason=>setError(reason instanceof Error?reason.message:String(reason))).finally(()=>setBusy(false));}}>{busy?'正在计算剩余范围…':'生成新方案'}</button>{error?<p role="alert">{error}</p>:null}{completed?<p role="status">方案已保存。到“运行”中显示或对比结果，也可以从“制图交付”生成报告。</p>:null}<details><summary>这次检查了什么</summary><p>检查填写的避让距离，保存输入图层版本和真实几何。最小连续面积、坡度、权属、道路通行与设施容量尚未纳入此流程；这些条件不能视为已满足。</p></details>{onPlan?<details><summary>接入路线、设施布局或其他条件</summary><p>Agent 先核对目标和所需数据，再组织可执行的步骤。没有路网或容量数据时，不会把圆形缓冲当作通行时间或承载能力。</p><label>你想比较什么<textarea aria-label="空间分析问题" value={question} onChange={event=>setQuestion(event.target.value)}/></label><button disabled={busy||!question.trim()} onClick={()=>{setBusy(true);setError('');void onPlan(question.trim()).catch(reason=>setError(String(reason))).finally(()=>setBusy(false));}}>交给 Agent 整理方案</button></details>:null}</section>;
}
