import { expect, test } from '@playwright/test';

test('rich conversation renders math, data, diagrams and controlled media', async ({ page }, testInfo) => {
  const failures: string[] = [];
  page.on('pageerror', error => failures.push(error.message));
  const externalImages: string[] = [];
  page.on('request', request => { if (request.url().includes('invalid.example')) externalImages.push(request.url()); });
  await page.goto('/e2e/fixtures/conversation-rich-v2.html');
  await expect(page.locator('math').first()).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('reading-light.png') });
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出可见行 CSV' }).first().click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toMatch(/\.csv$/);
  expect(await download.failure()).toBeNull();
  const code = page.locator('figure.paw-rich-code').filter({ hasText: 'receipt.ts' }).first();
  await code.getByRole('button', { name: '自动换行' }).click();
  await expect(code).toHaveAttribute('data-wrap', 'true');
  await code.getByRole('button', { name: '显示行号' }).click();
  await expect(code).toHaveAttribute('data-line-numbers', 'true');
  await page.getByRole('tab', { name: '结构', exact: true }).click();
  await expect(page.getByRole('region', { name: 'JSON 结构' })).toContainText('blocks');
  await page.getByRole('button', { name: '图表', exact: true }).click();
  await expect(page.getByRole('figure', { name: '示例数量柱形图' })).toBeVisible();
  const mermaid = page.getByTitle('Mermaid 图示', { exact: true });
  await page.locator('#rich-section-2').scrollIntoViewIfNeeded();
  await expect(mermaid).toBeVisible({ timeout: 30000 });
  await expect(mermaid).toHaveAttribute('sandbox', '');
  await expect(page.frameLocator('iframe[title="Mermaid 图示"]').locator('svg')).toBeVisible();
  await expect(page.getByTitle('静态 SVG 图示', { exact: true })).toHaveAttribute('sandbox', '');
  const opener = page.getByRole('button', { name: '放大图片：上一版工作台设计截图' });
  await opener.click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: '放大图片', exact: true }).click();
  await expect(dialog.locator('output')).toHaveText('125%');
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(opener).toBeFocused();
  await expect(page.locator('audio')).toHaveAttribute('controls', '');
  await expect(page.locator('video')).toHaveAttribute('controls', '');
  expect(externalImages).toEqual([]);
  await page.getByRole('button', { name: '深色', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  expect(await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.locator('#rich-section-0').scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('reading-dark.png') });
  expect(failures).toEqual([]);
});
