import { expect, test } from '@playwright/test';
import { expectNoHorizontalPageOverflow } from './helpers';

test('primary assistant discusses, delegates, stops, returns to work and edits the sourced profile', async ({ page }, info) => {
  test.setTimeout(90_000);
  await page.goto('/?controlTransport=mock#/agent');
  const agent = page.locator('.paw-window-shell[data-app="agent"]');
  await expect(agent).toBeVisible({ timeout: 30_000 });
  await expect(agent.locator('.paw-app-boot, .paw-app-loading')).toHaveCount(0, { timeout: 30_000 });
  await expect(agent.getByRole('button', { name: /打开对话/ })).toBeEnabled();
  await expectNoHorizontalPageOverflow(page);
  await info.attach('primary-assistant-home.png', { body: await page.screenshot(), contentType: 'image/png' });
  await agent.getByRole('textbox', { name: '和我的助手聊聊' }).fill('先帮我想清楚这个项目的目标');
  await agent.getByRole('button', { name: '发送给我的助手' }).click();
  await expect(agent.getByText('我的助手 · 长期对话', { exact: true })).toBeVisible();
  await expect(agent.getByText('讨论 · 只读', { exact: true })).toBeVisible();
  await expect(agent.locator('.paw-user-message', { hasText: '先帮我想清楚这个项目的目标' })).toHaveCount(1);
  await expect(agent.getByText('我们可以先把目标和顾虑说清楚。', { exact: false })).toBeVisible();
  await agent.getByRole('button', { name: '交给助手做', exact: true }).click();
  await expect(agent.getByRole('textbox', { name: '本次工作目录' })).toBeVisible();
  await agent.getByRole('textbox', { name: '和我的助手聊聊' }).fill('检查工作台的对话入口');
  await agent.getByRole('textbox', { name: '完成标准' }).fill('保留执行过程与结果');
  await agent.getByRole('textbox', { name: '本次工作目录' }).fill('/work/demo');
  await expect(agent.getByRole('button', { name: '授权并开始任务' })).toBeDisabled();
  await agent.getByRole('checkbox').check();
  await info.attach('primary-assistant-execution-scope.png', { body: await page.screenshot(), contentType: 'image/png' });
  await agent.getByRole('button', { name: '授权并开始任务' }).click();
  await expect(agent.getByText('当前工作', { exact: true })).toBeVisible();
  await expect(agent.getByText('本次工作区已授权', { exact: true })).toBeVisible();
  const stop = agent.getByRole('button', { name: '停止本轮', exact: true });
  await expect(stop).toBeVisible();
  await stop.click();
  await expect(stop).toBeHidden();
  await page.waitForTimeout(4200);
  await expect(agent.getByText('这是演示任务的结果：', { exact: false })).toHaveCount(0);
  await info.attach('primary-assistant-stopped.png', { body: await page.screenshot(), contentType: 'image/png' });
  await agent.getByRole('button', { name: '返回我的助手', exact: true }).click();
  const task = agent.getByRole('button', { name: /检查工作台的对话入口.*任务未完成/ });
  await expect(task).toBeVisible();
  await task.click();
  await agent.getByRole('textbox', { name: '消息', exact: true }).fill('继续检查，给我结果');
  await agent.getByRole('button', { name: '发送', exact: true }).click();
  await expect(agent.getByTestId('virtuoso-item-list').getByText('这是演示任务的结果：', { exact: false })).toBeVisible({ timeout: 10000 });
  await info.attach('primary-assistant-result.png', { body: await page.screenshot(), contentType: 'image/png' });
  await agent.getByRole('button', { name: '返回我的助手', exact: true }).click();
  await expect(agent.getByRole('button', { name: /检查工作台的对话入口.*已完成/ })).toBeVisible();
  await agent.getByRole('button', { name: '关于我', exact: true }).click();
  const memory = page.locator('.paw-window-shell[data-app="memory"]');
  const paragraph = memory.getByRole('textbox', { name: '个人背景 1' });
  await expect(paragraph).toHaveValue('我在做一个本地优先的个人工作台。');
  await paragraph.fill('我在做本地优先的工作台，希望交流简洁、执行有清楚的范围。');
  await memory.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(memory.getByRole('button', { name: '已保存', exact: true })).toBeVisible();
  await expect(paragraph).toHaveValue('我在做本地优先的工作台，希望交流简洁、执行有清楚的范围。');
  await expect(memory.getByRole('button', { name: '来源 1', exact: true }).first()).toBeVisible();
  await expectNoHorizontalPageOverflow(page);
  await info.attach('primary-assistant-profile.png', { body: await page.screenshot(), contentType: 'image/png' });
});
